# api/config/schema.yaml
# The list of types and properties we want to use
types:
  # Parent class of Person
  Thing:
    properties:
      name: ~
  User:
    properties:
      familyName: { range: "Text" }
      givenName: { range: "Text" }
      username: { range: "Text" }
      password: { range: "Text" }
      isActive: { range: "Boolean" }
      address: { range: "Text" }
  PostalAddress:
    # Disable the generation of the class hierarchy for this type
    parent: false
    properties:
      # Force the type of the addressCountry property to text
      addressCountry: { range: "Text" }
      addressLocality: ~
      addressRegion: ~
      postOfficeBoxNumber: ~
      postalCode: ~
      streetAddress:
  Wehicle:
    properties:
      Producer: { range: "Text" }
      DateProduction: { range: "Date" }
      Type: { range: "Text" }
      Model: { range: "Text" }


